### PR TITLE
fix build script to build all instances

### PR DESCRIPTION
**Pull request by djrrb**

### CODE REVIEW

**Comment by djrrb** [comment]
@m4rc1e I’m not sure if I did this correctly, but I’m attempting to submit a PR that fixes the build script to get all instances built. sorry about that, and hmu if I should do something differently

**Comment by djrrb** [comment]
@googlebot I fixed it.

**Comment by pichotta** [comment]
@googlebot I fixed it.

**Comment by pichotta** [comment]
@m4rc1e  @djrrb 
Is there an action item need to resolve the CLA?

**Pull request closed without merging**
